ShopManagingSystem/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SMS_DataAccess.Data;
using SMS_DataAccess.Repository.IRepository;
using SMS_Models;
using SMS_Utility;
using System.Data;

namespace ShopManagingSystem.Controllers
{
    [Authorize(Roles = WebConstant.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _applicationTypeRepository;

        public ApplicationTypeController(IApplicationTypeRepository applicationTypeRepository) 
        {
            _applicationTypeRepository = applicationTypeRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<ApplicationType> applicationTypes = _applicationTypeRepository.GetAll();
            return View(applicationTypes);
        }

        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType applicationType)
        {
            _applicationTypeRepository.Add(applicationType);
            _applicationTypeRepository.Save();
            return RedirectToAction("Index");
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _applicationTypeRepository.Find(id.GetValueOrDefault());

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType applicationType)
        {
            if (ModelState.IsValid)
            {
                _applicationTypeRepository.Update(applicationType);
                _applicationTypeRepository.Save();
                return RedirectToAction("Index");
            }
            return View(applicationType);
        }

        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _applicationTypeRepository.Find(id.GetValueOrDefault());

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {
            var category = _applicationTypeRepository.Find(id.GetValueOrDefault());

            if (category == null)
                return NotFound();

            _applicationTypeRepository.Remove(category);
            _applicationTypeRepository.Save();
            return RedirectToAction("Index");
        }

    }
}

ShopManagingSystem/Views/ApplicationType/Create.cshtml
@model ApplicationType

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row mb-5">
            <h2 class="text-info pl-3">Add Application Type</h2>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group row mb-3">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row mb-3">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

ShopManagingSystem/Views/ApplicationType/Delete.cshtml
@model ApplicationType

<form method="post" asp-action="DeleteConfirmed">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row mb-5">
            <h2 class="text-info pl-3">Delete Category</h2>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group row mb-3">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row mb-3">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

ShopManagingSystem/Views/ApplicationType/Edit.cshtml
@model             ApplicationType

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row mb-5">
            <h2 class="text-info pl-3">Edit Category</h2>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group row mb-3">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row mb-3">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

ShopManagingSystem/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>

<div class="container p-3">
    <div class="form-group row">
        <div class="col-6 pt-4">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 pt-4 text-md-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fa-solid fa-plus"></i> &nbsp; Create new application type
            </a>
        </div>
    </div>

    <br /><br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped bg-white" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var applicationType in Model)
                {
                    <tr>
                        <td width="50%">@applicationType.Name</td>
                        <td class="text-center">
                            <div class="w-75% btn-group" role="group">
                                <a asp-controller="ApplicationType" asp-route-Id="@applicationType.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fa-solid fa-pencil"></i>
                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@applicationType.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="fa-solid fa-trash-can"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Applications aren't exist</p>
    }
</div>